# _config.yml

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "default"

title: "Csaba Kobol"
name: "Csaba Kobol"
description: "Helping teams deliver better software with expert QA, automation, and practical testing insights."
url: "https://kobolcs.github.io"
baseurl: ""

# Single sass configuration
sass:
  sass_dir: assets/_sass
  style: compressed
  load_paths:
    - assets/_sass

# Single plugins list
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Top-level defaults to inject custom.js
defaults:
  -
    scope:
      path: ""
    values:
      custom_js:
        - /assets/js/custom.js

author:
  name: "Csaba Kobol"
  avatar: "/assets/images/avatar_home_512.png"
  bio: "QA and Test Automation Consultant with over a decade of experience…"
  location: "Remote, EU"
  links:
    - label: "Email"
      icon: "fas fa-envelope-square"
      url: "mailto:conta@csabakobol.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/csabakobol"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/kobolcs"

footer:
  links:
    - label: "Privacy Policy"
      url: "/privacy/"
    - label: "Terms of Service"
      url: "/terms/"
    - label: "LinkedIn"
      icon: "fab fa-linkedin grey-icon"
      url: "https://linkedin.com/in/csabakobol"
    - label: "GitHub"
      icon: "fab fa-github grey-icon"
      url: "https://github.com/kobolcs"
